const recipes = [
  {
    id: 0,
    name: "Beef Stir-Fry with Vegetables",
    description:
      "A quick and flavorful beef stir-fry featuring tender strips of beef, colorful vegetables, and a savory soy-based sauce.",
    ingredients: [
      "1 pound flank steak, thinly sliced against the grain",
      "3 tablespoons soy sauce",
      "2 tablespoons oyster sauce",
      "1 tablespoon hoisin sauce",
      "1 tablespoon cornstarch",
      "2 tablespoons vegetable oil",
      "3 cloves garlic, minced",
      "1 tablespoon fresh ginger, grated",
      "1 red bell pepper, thinly sliced",
      "1 yellow bell pepper, thinly sliced",
      "1 broccoli crown, cut into florets",
      "2 carrots, julienned",
      "4 green onions, sliced",
      "1 tablespoon sesame oil (for finishing)",
      "Cooked white rice, for serving",
    ],
    instructions: [
      "In a bowl, mix soy sauce, oyster sauce, hoisin sauce, and cornstarch. Add sliced beef, ensuring it's well-coated. Let it marinate for 15-20 minutes.",
      "Heat vegetable oil in a wok or large skillet over high heat.",
      "Add marinated beef to the hot wok, spreading it out in an even layer. Allow it to sear for 1-2 minutes without stirring to achieve a nice caramelization.",
      "Stir-fry beef until browned and cooked through. Remove beef from the wok and set aside.",
      "In the same wok, add a bit more oil if needed. Stir-fry garlic and ginger until fragrant.",
      "Add sliced bell peppers, broccoli florets, and julienned carrots to the wok. Stir-fry until vegetables are crisp-tender.",
      "Return the cooked beef to the wok with the vegetables.",
      "Pour the sesame oil over the stir-fry and toss everything together until well combined.",
      "Garnish with sliced green onions and serve the beef stir-fry over cooked white rice.",
      "Enjoy your delicious Beef Stir-Fry with Vegetables!",
    ],
    cookTime: "25 minutes",
    image: "beef_stir_fry.jpg",
    category: "Beef",
    iframe: "https://www.youtube.com/embed/cyS8ycmGs1U?si=tSq-ThrwMOXCHIUu",
  },
  {
    id: 1,
    name: "Chicken Karaage",
    description:
      "Japanese-style fried chicken featuring bite-sized, marinated, and deep-fried chicken pieces with a crispy exterior and juicy, flavorful interior.",
    ingredients: [
      "1 pound boneless, skinless chicken thighs, cut into bite-sized pieces",
      "3 tablespoons soy sauce",
      "2 tablespoons sake (Japanese rice wine) or dry sherry",
      "1 tablespoon grated fresh ginger",
      "2 cloves garlic, minced",
      "1 tablespoon sesame oil",
      "1 cup potato starch or cornstarch, for coating",
      "Vegetable oil, for deep-frying",
      "Lemon wedges, for serving (optional)",
    ],
    instructions: [
      "In a bowl, mix together soy sauce, sake, grated ginger, minced garlic, and sesame oil to create the marinade.",
      "Add chicken pieces to the marinade, ensuring they are well-coated. Cover and marinate in the refrigerator for at least 30 minutes.",
      "Heat vegetable oil in a deep fryer or large, deep pan to 350-375°F (175-190°C).",
      "Remove the marinated chicken from the refrigerator and let it come to room temperature.",
      "Place potato starch or cornstarch in a shallow dish. Coat each piece of marinated chicken thoroughly with starch, shaking off excess.",
      "Carefully place coated chicken pieces into the hot oil, ensuring not to overcrowd the pan. Fry until golden brown and crispy, about 5-6 minutes.",
      "Use a slotted spoon to remove chicken from the oil and place on a plate lined with paper towels to absorb excess oil.",
      "Repeat the frying process with the remaining chicken pieces.",
      "Serve the chicken karaage hot, optionally garnished with lemon wedges for squeezing over the top. Enjoy as an appetizer, snack, or part of a meal.",
    ],
    cookTime: "30 minutes",
    image: "chicken_karaage.jpg",
    category: "Chicken",
    iframe: "https://www.youtube.com/embed/Knw6pDVM_WI?si=cFwRxgHS75kmebfE",
  },
  {
    id: 2,
    name: "Beef Steak (Bistek Tagalog)",
    description:
      "Filipino beef steak marinated and cooked with soy sauce, calamansi juice, and garlic.",
    ingredients: [
      "1 pound beef sirloin, thinly sliced",
      "1/2 cup soy sauce",
      "1/4 cup calamansi juice (or lemon juice)",
      "4 cloves garlic, minced",
      "1 onion, sliced into rings",
      "1/2 teaspoon pepper",
      "2 tablespoons cooking oil",
      "1 cup water",
      "Salt to taste",
    ],
    instructions: [
      "In a bowl, combine soy sauce, calamansi juice, minced garlic, and pepper. Marinate the beef slices for at least 30 minutes.",
      "Heat cooking oil in a pan. Sauté onion rings until soft and translucent. Set aside.",
      "In the same pan, pan-fry the marinated beef slices until browned on both sides.",
      "Add the marinade and water. Simmer until the beef is tender and the sauce thickens.",
      "Season with salt to taste.",
      "Top the beef slices with sautéed onions.",
      "Serve hot and enjoy your Beef Steak (Bistek Tagalog) over steamed rice!",
    ],
    cookTime: "1 hour",
    image: "beef_steak.jpg",
    category: "Beef",
    iframe: "https://www.youtube.com/embed/xH746HwUlbQ?si=-aPSBxV0fWEsePS6",
  },
  {
    id: 3,
    name: "Kusido",
    description:
      "A hearty Filipino fish stew with a medley of vegetables and rich broth.",
    ingredients: [
      "1 pound fish fillet (maya-maya, lapu-lapu, or any firm white fish)",
      "1 cup potatoes, diced",
      "1 cup carrots, sliced",
      "1 cup green bell pepper, sliced",
      "1 cup corn kernels",
      "1 onion, chopped",
      "3 cloves garlic, minced",
      "2 tomatoes, diced",
      "1 thumb-sized ginger, julienned",
      "2 green chili peppers",
      "1/4 cup fish sauce",
      "1 teaspoon ground black pepper",
      "2 tablespoons cooking oil",
      "4 cups fish or vegetable broth",
    ],
    instructions: [
      "In a pot, heat cooking oil and sauté garlic, onion, and ginger until fragrant.",
      "Add tomatoes and cook until softened.",
      "Pour in fish or vegetable broth. Bring to a boil.",
      "Add fish fillet, potatoes, carrots, green bell pepper, corn, and green chili peppers.",
      "Simmer until the fish is cooked and the vegetables are tender.",
      "Season with fish sauce and ground black pepper. Adjust to taste.",
      "Serve hot and enjoy your comforting Fish Cocido with steamed rice!",
    ],
    cookTime: "45 minutes",
    image: "kusido.jpg",
    category: "Seafood",
    iframe: "https://www.youtube.com/embed/-eLubho5Rh4?si=G-96-YHWQFkrjovq",
  },
  {
    id: 4,
    name: "Nilagang Baka",
    description:
      "A hearty Filipino beef soup with boiled beef, corn on the cob, and various vegetables.",
    ingredients: [
      "2 pounds beef shank, cut into serving pieces",
      "4 pieces corn on the cob, each cut into 3 parts",
      "4 pieces saba banana, peeled and halved",
      "2 pieces potato, peeled and quartered",
      "2 pieces sweet potato, peeled and quartered",
      "1 bundle pechay (bok choy), leaves separated",
      "1 piece plantain banana (saging na saba), peeled and halved",
      "1 medium-sized onion, peeled and quartered",
      "4 cloves garlic, peeled and crushed",
      "Salt to taste",
      "Pepper to taste",
      "Fish sauce or shrimp paste (bagoong) for dipping",
    ],
    instructions: [
      "In a large pot, combine beef shank, onion, and garlic. Add enough water to cover the meat.",
      "Bring to a boil and skim off any scum that rises to the surface.",
      "Lower the heat and let it simmer until the beef is tender, usually takes about 2-3 hours.",
      "Once the beef is tender, add corn on the cob, saba banana, plantain banana, potato, and sweet potato. Simmer until the vegetables are cooked.",
      "Season with salt and pepper to taste.",
      "Add pechay leaves and cook for an additional 2 minutes or until the leaves are wilted.",
      "Serve hot and enjoy your comforting Nilagang Baka with fish sauce or shrimp paste on the side.",
    ],
    cookTime: "2-3 hours",
    image: "nilagang_baka.jpg",
    category: "Beef",
    iframe: "https://www.youtube.com/embed/dqtslBVdQ2Q?si=QgirVB9kQwx4zvfp",
  },
  {
    id: 5,
    name: "Pork Sisig",
    description:
      "A popular Filipino dish made from minced pork, usually served on a sizzling plate. It's known for its savory, sour, and slightly spicy flavors.",
    ingredients: [
      "1 pound pork belly, finely chopped",
      "1 onion, minced",
      "3 cloves garlic, minced",
      "3-4 green chili peppers, minced",
      "1 red chili pepper, minced (optional for extra heat)",
      "1 tablespoon soy sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon mayonnaise",
      "1 tablespoon calamansi or lemon juice",
      "Salt and pepper to taste",
      "Cooking oil for sautéing",
      "Chopped green onions and sliced red chili for garnish",
      "Sizzling plate for serving",
    ],
    instructions: [
      "In a pan, heat cooking oil over medium heat. Sauté minced garlic until golden brown.",
      "Add minced pork belly and cook until it turns crispy and golden brown.",
      "Add minced onion, green chili peppers, and red chili pepper (if using). Sauté until the onions are translucent.",
      "Stir in soy sauce, oyster sauce, and mayonnaise. Mix well to coat the pork evenly.",
      "Season with salt and pepper to taste. Cook for a few more minutes until everything is well combined.",
      "Drizzle calamansi or lemon juice over the sisig and mix thoroughly.",
      "Transfer the Pork Sisig to a sizzling plate, garnish with chopped green onions and sliced red chili, and serve hot.",
      "Enjoy your sizzling and flavorful Pork Sisig with steamed rice!",
    ],
    cookTime: "30 minutes",
    image: "pork_sisig.jpg",
    category: "Pork",
    iframe: "https://www.youtube.com/embed/kapD-91ZUH8?si=K_KxizGwIITAA4Kv",
  },
  {
    id: 6,
    name: "Escabeche",
    description:
      "Filipino sweet and sour fish: Fried fish, tangy sauce, colorful veggies—delightful for special occasions.",
    ingredients: [
      "1 whole fish (tilapia or lapu-lapu), cleaned and scaled",
      "1 cup flour, for dredging",
      "Salt and pepper to taste",
      "Cooking oil for frying",
      "1 red bell pepper, sliced into strips",
      "1 green bell pepper, sliced into strips",
      "1 carrot, julienned",
      "1 onion, sliced into rings",
      "3 cloves garlic, minced",
      "1 thumb-sized ginger, julienned",
      "1/2 cup vinegar",
      "1/2 cup water",
      "1/4 cup soy sauce",
      "1/4 cup sugar",
      "1 tablespoon cornstarch, dissolved in 2 tablespoons water",
      "Salt and pepper to taste",
      "Green onions for garnish",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Clean and scale the whole fish. Dredge the fish in flour, salt, and pepper, then fry until golden brown and crispy. Set aside.",
      "In a separate pan, sauté garlic and ginger until aromatic. Add the sliced onions, bell peppers, and julienned carrots. Stir-fry until the vegetables are slightly tender.",
      "In a bowl, mix together vinegar, water, soy sauce, and sugar to create the sweet and sour sauce. Pour the sauce into the pan with vegetables and bring to a simmer.",
      "Add the dissolved cornstarch to the sauce to thicken it. Adjust the taste with salt and pepper if needed.",
      "Place the fried fish on a serving plate and pour the sweet and sour sauce over it, ensuring the fish is well-coated.",
      "Garnish with green onions and sesame seeds for added flavor and presentation.",
      "Serve the Escabeche hot with steamed rice and enjoy this delightful sweet and sour fish dish!",
    ],
    cookTime: "30 minutes",
    image: "escabeche.jpg",
    category: "Seafood",
    iframe: "https://www.youtube.com/embed/4tQd79faZVE?si=w0RhprRu7qt-BqbM",
  },
  {
    id: 7,
    name: "Garlic Butter Baked Chicken",
    description:
      "Juicy and flavorful baked chicken thighs with a delicious garlic butter sauce.",
    ingredients: [
      "4 bone-in, skin-on chicken thighs",
      "Salt and black pepper to taste",
      "1 teaspoon paprika",
      "1 teaspoon dried thyme",
      "1 teaspoon garlic powder",
      "4 tablespoons unsalted butter, melted",
      "4 cloves garlic, minced",
      "1 tablespoon fresh parsley, chopped (for garnish)",
    ],
    instructions: [
      "Preheat the oven to 400°F (200°C).",
      "Pat the chicken thighs dry with paper towels. Season both sides with salt, black pepper, paprika, dried thyme, and garlic powder.",
      "Place the seasoned chicken thighs in a baking dish, skin side up.",
      "In a small bowl, mix melted butter and minced garlic. Pour the garlic butter mixture over the chicken thighs.",
      "Bake in the preheated oven for 30-35 minutes or until the chicken reaches an internal temperature of 165°F (74°C) and the skin is crispy.",
      "Baste the chicken with the garlic butter sauce halfway through the baking time.",
      "Once done, remove from the oven and let it rest for a few minutes.",
      "Garnish with chopped fresh parsley before serving.",
      "Serve hot and enjoy your Garlic Butter Baked Chicken with your favorite side dishes!",
    ],
    cookTime: "35 minutes",
    image: "garlic_butter_baked_chicken.jpg",
    category: "Chicken",
    iframe: "https://www.youtube.com/embed/eF4jk8yelMc?si=A-nvhCr98rgujTK-",
  },
  {
    id: 8,
    name: "Beef and Mushroom Stroganoff",
    description:
      "A comforting and creamy beef stroganoff with tender strips of beef, mushrooms, and a rich sour cream sauce.",
    ingredients: [
      "1 pound beef sirloin or tenderloin, thinly sliced",
      "Salt and black pepper to taste",
      "2 tablespoons olive oil",
      "1 onion, finely chopped",
      "2 cloves garlic, minced",
      "8 oz (about 225g) mushrooms, sliced",
      "2 tablespoons all-purpose flour",
      "1 cup beef broth",
      "2 tablespoons Worcestershire sauce",
      "1 tablespoon Dijon mustard",
      "1/2 cup sour cream",
      "Egg noodles or rice, for serving",
      "Fresh parsley, chopped, for garnish",
    ],
    instructions: [
      "Season the sliced beef with salt and black pepper.",
      "In a large skillet, heat olive oil over medium-high heat. Add the sliced beef and sear until browned. Remove beef from the skillet and set aside.",
      "In the same skillet, add chopped onion and minced garlic. Sauté until onions are softened.",
      "Add sliced mushrooms to the skillet and cook until they release their moisture and become golden brown.",
      "Sprinkle flour over the vegetables and stir to combine. Cook for 1-2 minutes to remove the raw flour taste.",
      "Gradually whisk in beef broth, Worcestershire sauce, and Dijon mustard. Bring the mixture to a simmer, allowing it to thicken.",
      "Return the cooked beef to the skillet and stir in sour cream. Simmer for a few more minutes until the beef is heated through.",
      "Serve the Beef and Mushroom Stroganoff over cooked egg noodles or rice.",
      "Garnish with chopped fresh parsley before serving.",
      "Enjoy your comforting and creamy Beef and Mushroom Stroganoff!",
    ],
    cookTime: "30 minutes",
    image: "beef_mushroom_stroganoff.jpg",
    category: "Beef",
    iframe: "https://www.youtube.com/embed/7r3dlmYUf4s?si=iNm_Fbq4ywIDDMrU",
  },
  {
    id: 9,
    name: "Chicken Adobo",
    description:
      "A savory and slightly tangy dish made with meat, soy sauce, vinegar, and garlic.",
    ingredients: [
      "1.5 to 2 pounds chicken pieces (legs, thighs, or a combination)",
      "1 onion, peeled and sliced thinly",
      "1 head of garlic, peeled and minced",
      "1 cup soy sauce",
      "1 cup white vinegar",
      "1 teaspoon whole peppercorns",
      "2 bay leaves",
      "1 tablespoon cooking oil",
      "1 cup water (optional, for a less intense flavor)",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine the chicken, soy sauce, vinegar, minced garlic, and peppercorns.",
      "Marinate the chicken in the refrigerator for at least 30 minutes to an hour. For a richer flavor, marinate it longer, even overnight.",
      "Heat oil in a wide, heavy-bottomed skillet or pot over medium heat.",
      "Add the sliced onions and cook until they become soft and translucent.",
      "Add the marinated chicken, including the marinade, to the pot.",
      "Add bay leaves and bring the mixture to a boil. Boil for 2-3 minutes.",
      "Reduce heat to low, cover, and let it simmer for about 30-40 minutes or until the chicken is tender. Add water if you want to mellow down the flavor.",
      "Stir occasionally to make sure the chicken is evenly coated with the sauce.",
      "Taste the adobo and adjust the seasoning by adding salt and pepper according to your preference.",
      "Serve the Chicken Adobo over steamed rice.",
    ],
    cookTime: "1 hour",
    image: "chicken_adobo.jpg",
    category: "Chicken",
    iframe: "https://www.youtube.com/embed/wwapBsT0oc8?si=sSSnF2gkjl93v9Fr",
  },
  {
    id: 10,
    name: "Pork Sinigang",
    description: "A sour tamarind-based soup with various vegetables and pork.",
    ingredients: [
      "1 pound pork ribs or pork belly, cut into serving pieces",
      "1 packet (about 1.4 ounces) sinigang mix (tamarind soup base)",
      "1 onion, peeled and sliced",
      "1 tomato, sliced",
      "1 radish, peeled and sliced",
      "1 cup string beans, cut into 2-inch lengths",
      "1 bunch water spinach (kangkong), washed and trimmed",
      "2 eggplants, sliced",
      "2 green chili peppers",
      "Salt and fish sauce to taste",
    ],
    instructions: [
      "In a pot, bring about 8 cups of water to a boil.",
      "Add pork ribs or pork belly and sinigang mix. Simmer until pork is tender.",
      "Add sliced onion and tomato. Continue simmering until vegetables are almost tender.",
      "Add radish, string beans, eggplants, and green chili peppers. Simmer until all vegetables are cooked.",
      "Season with salt and fish sauce to taste.",
      "Serve hot and enjoy your Pork Sinigang!",
    ],
    cookTime: "45 minutes",
    image: "pork_sinigang.jpg",
    category: "Pork",
    iframe: "https://www.youtube.com/embed/CzBF1IhIn1M?si=FlZUw_PxSTq-G6pV",
  },
  {
    id: 11,
    name: "Pinakbet",
    description:
      "A flavorful Filipino vegetable dish made with mixed vegetables and shrimp paste.",
    ingredients: [
      "1/2 pound pork belly, sliced",
      "1 cup squash, peeled and sliced",
      "1 cup eggplant, sliced",
      "1 cup okra",
      "1 cup string beans, cut into 2-inch pieces",
      "1 medium-sized bitter gourd (ampalaya), sliced",
      "2 medium-sized tomatoes, sliced",
      "1 medium-sized onion, sliced",
      "4 cloves garlic, minced",
      "2 tablespoons shrimp paste (bagoong)",
      "2 cups water",
      "Salt and pepper to taste",
      "2 tablespoons cooking oil",
    ],
    instructions: [
      "In a pot, heat oil and sauté garlic, onion, and tomatoes until soft.",
      "Add pork belly and cook until browned.",
      "Stir in shrimp paste and cook for a few minutes.",
      "Pour water into the pot and bring it to a boil.",
      "Add squash, eggplant, bitter gourd, string beans, and okra. Simmer until vegetables are tender.",
      "Season with salt and pepper to taste.",
      "Serve hot and enjoy your Pinakbet!",
    ],
    cookTime: "45 minutes",
    image: "pinakbet.jpg",
    category: "Vegetable",
    iframe: "https://www.youtube.com/embed/OzfTQZVYKmY?si=hkH4YrJZMNl5ZDTJ",
  },
  {
    id: 12,
    name: "Paksiw na Isda",
    description:
      "A Filipino dish of fish cooked in vinegar, garlic, ginger, and spices for a flavorful and tangy taste.",
    ingredients: [
      "1 pound fish (mackerel, bangus/milkfish, or any firm-fleshed fish), cleaned and sliced",
      "1/2 cup vinegar",
      "1/2 cup soy sauce",
      "1 cup water",
      "1 thumb-sized ginger, sliced",
      "4 cloves garlic, minced",
      "1 onion, sliced",
      "2-3 pieces green chili peppers",
      "1 teaspoon peppercorns",
      "2 bay leaves",
      "Salt to taste",
      "2 tablespoons cooking oil",
    ],
    instructions: [
      "In a wide pan, arrange fish slices at the bottom.",
      "In a bowl, mix vinegar, soy sauce, water, ginger, garlic, onion, green chili peppers, peppercorns, and bay leaves.",
      "Pour the mixture over the fish slices. Add salt to taste.",
      "Cover and simmer over medium heat until the fish is cooked and the sauce thickens.",
      "Drizzle with cooking oil and continue to simmer for a few more minutes.",
      "Serve hot and enjoy your Paksiw na Isda with steamed rice!",
    ],
    cookTime: "30 minutes",
    image: "paksiw_na_isda.jpg",
    category: "Seafood",
    iframe: "https://www.youtube.com/embed/IM2jDoGwX_w?si=DqNA-8VElOctdvqE",
  },
  {
    id: 13,
    name: "Chopsuey",
    description:
      "A delightful mixed vegetable stir-fry with meat, commonly served in a savory sauce.",
    ingredients: [
      "1/2 pound chicken breast, sliced",
      "1/2 pound pork, thinly sliced",
      "1 cup shrimp, peeled and deveined",
      "1 cup cauliflower florets",
      "1 cup broccoli florets",
      "1 cup snow peas",
      "1 cup carrots, sliced",
      "1 cup bell peppers, sliced",
      "1 cup cabbage, shredded",
      "1 cup baby corn, halved",
      "1 cup mushrooms, sliced",
      "1 cup chicken broth",
      "3 tablespoons oyster sauce",
      "2 tablespoons soy sauce",
      "1 tablespoon cornstarch, dissolved in water",
      "3 cloves garlic, minced",
      "1 medium-sized onion, sliced",
      "2 tablespoons cooking oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a wok or large pan, heat oil and sauté garlic and onions until fragrant.",
      "Add chicken and pork slices. Cook until browned.",
      "Add shrimp and continue cooking until they turn pink.",
      "Stir in vegetables - cauliflower, broccoli, snow peas, carrots, bell peppers, cabbage, baby corn, and mushrooms.",
      "In a bowl, mix chicken broth, oyster sauce, soy sauce, and dissolved cornstarch. Pour the mixture into the pan.",
      "Season with salt and pepper to taste. Stir well.",
      "Simmer until the vegetables are cooked but still crisp.",
      "Serve hot and enjoy your delicious Chopsuey!",
    ],
    cookTime: "30 minutes",
    image: "chopsuey.jpg",
    category: "Vegetable",
    iframe: "https://www.youtube.com/embed/kDtSZTzkGYM?si=uwjOnp38LJyrgtMR",
  },
  {
    id: 14,
    name: "Lechon Kawali",
    description: "Crispy fried pork belly served with a side of liver sauce.",
    ingredients: [
      "Pork belly",
      "Salt",
      "Pepper",
      "Garlic",
      "Water",
      "Oil for frying",
    ],
    instructions: [
      "Boil pork belly until tender.",
      "Air-dry or refrigerate to dry the skin.",
      "Deep fry until crispy.",
      "Serve with liver sauce.",
    ],
    cookTime: "1.5 hours",
    image: "lechon_kawali.jpg",
    category: "Pork",
    iframe: "https://www.youtube.com/embed/MPY9EmLFaR0?si=0MKRAFxLm1RkLCfo",
  },
  {
    id: 15,
    name: "Menudo",
    description:
      "A hearty Filipino stew made with pork, liver, potatoes, carrots, and bell peppers in a flavorful tomato sauce.",
    ingredients: [
      "1 pound pork, cut into small cubes",
      "1/2 cup pork liver, sliced into small pieces",
      "1 large potato, peeled and diced",
      "1 carrot, peeled and diced",
      "1 red bell pepper, diced",
      "1 green bell pepper, diced",
      "1 onion, chopped",
      "4 cloves garlic, minced",
      "1 cup tomato sauce",
      "1/2 cup soy sauce",
      "1/2 cup water",
      "1 teaspoon sugar",
      "Salt and pepper to taste",
      "3 tablespoons cooking oil",
    ],
    instructions: [
      "In a pan, heat cooking oil and sauté garlic and onion until fragrant.",
      "Add pork and liver. Cook until browned.",
      "Stir in tomato sauce, soy sauce, and water. Simmer for 15-20 minutes.",
      "Add potatoes, carrots, and bell peppers. Continue cooking until vegetables are tender.",
      "Season with sugar, salt, and pepper to taste.",
      "Simmer for an additional 10-15 minutes until the sauce thickens.",
      "Serve hot and enjoy your delicious Menudo with steamed rice!",
    ],
    cookTime: "45 minutes",
    image: "menudo.jpg",
    category: "Pork",
    iframe: "https://www.youtube.com/embed/7i_RmZwkNpI?si=1QTcelY9F29YMmU5",
  },
  {
    id: 16,
    name: "Tortang Talong",
    description:
      "A Filipino eggplant omelette typically served with rice and a side of fish sauce or vinegar dip.",
    ingredients: [
      "4 large eggplants",
      "3 large eggs",
      "Salt to taste",
      "Pepper to taste",
      "Cooking oil for frying",
      "Fish sauce or vinegar for dipping",
    ],
    instructions: [
      "Roast the eggplants over an open flame or grill until the skin is charred and the flesh is soft. Allow them to cool.",
      "Peel the skin off the eggplants, leaving the stems intact. Flatten the eggplants by gently pressing down on them with the back of a fork or spoon.",
      "In a bowl, beat the eggs and season with salt and pepper to taste.",
      "Dip each flattened eggplant in the beaten eggs, making sure to coat both sides.",
      "In a pan, heat cooking oil over medium heat. Fry the egg-coated eggplants until golden brown on both sides.",
      "Place the fried eggplants on a serving plate and serve hot with fish sauce or vinegar on the side.",
      "Enjoy your delicious Tortang Talong with steamed rice!",
    ],
    cookTime: "30 minutes",
    image: "tortang_talong.jpg",
    category: "Vegetable",
    iframe: "https://www.youtube.com/embed/bCWkcaQC9Ck?si=MitACgG3IC-CDwcf",
  },
  {
    id: 17,
    name: "Mongolian Beef",
    description:
      "A delicious and savory Mongolian beef stir-fry with tender strips of beef, green onions, and a flavorful soy-based sauce.",
    ingredients: [
      "1 pound flank steak, thinly sliced against the grain",
      "1/4 cup cornstarch",
      "3 tablespoons vegetable oil",
      "3 cloves garlic, minced",
      "1 tablespoon fresh ginger, grated",
      "1/2 cup low-sodium soy sauce",
      "1/2 cup water",
      "1/2 cup brown sugar",
      "1/2 cup green onions, sliced (for garnish)",
      "1 tablespoon sesame seeds (for garnish)",
      "Cooked white rice, for serving",
    ],
    instructions: [
      "In a bowl, coat the sliced beef with cornstarch, ensuring each piece is evenly coated.",
      "Heat 2 tablespoons of vegetable oil in a wok or large skillet over medium-high heat.",
      "Add the coated beef to the hot wok and stir-fry until browned and crispy. Remove beef from the wok and set aside.",
      "In the same wok, add the remaining tablespoon of vegetable oil. Stir-fry garlic and ginger until fragrant.",
      "In a bowl, mix soy sauce, water, and brown sugar. Pour the sauce into the wok and bring it to a simmer, allowing it to thicken slightly.",
      "Return the cooked beef to the wok, tossing it in the sauce until well-coated.",
      "Serve the Mongolian Beef over cooked white rice, garnished with sliced green onions and sesame seeds.",
      "Enjoy your flavorful and savory Mongolian Beef!",
    ],
    cookTime: "20 minutes",
    image: "mongolian_beef.jpg",
    category: "Beef",
    iframe: "https://www.youtube.com/embed/zsAut4x1qt4?si=0UCkV80VsPKDtWrd",
  },
  {
    id: 18,
    name: "Adobong Manok sa Gata",
    description:
      "A delicious Filipino chicken adobo with a twist, cooked with coconut milk for a creamy and savory flavor.",
    ingredients: [
      "1.5 to 2 pounds chicken pieces (legs, thighs, or a combination)",
      "1 onion, peeled and sliced thinly",
      "4 cloves garlic, peeled and minced",
      "1 cup coconut milk",
      "1 cup soy sauce",
      "1 cup vinegar",
      "1 teaspoon whole peppercorns",
      "2 bay leaves",
      "1 tablespoon cooking oil",
      "1 cup water (optional, for a less intense flavor)",
      "Salt to taste",
      "Pepper to taste",
    ],
    instructions: [
      "Marinate the chicken in a mixture of soy sauce, vinegar, minced garlic, and peppercorns for at least 30 minutes to an hour.",
      "Heat oil in a pot and sauté sliced onions until soft and translucent.",
      "Add the marinated chicken, bay leaves, and bring to a boil. Boil for 2-3 minutes.",
      "Reduce heat to low, cover, and simmer for 30-40 minutes or until the chicken is tender. Add water if desired.",
      "Adjust seasoning with salt and pepper according to your preference.",
      "Pour in coconut milk and simmer for an additional 10-15 minutes or until the sauce thickens.",
      "Serve the Adobong Manok sa Gata over steamed rice.",
    ],
    cookTime: "1 hour",
    image: "adobong_manok_gata.jpg",
    category: "Chicken",
    iframe: "https://www.youtube.com/embed/hULeqITt_S4?si=MiZohho1S3dC0A81",
  },
  {
    id: 19,
    name: "Beef Tapa",
    description:
      "Beef Tapa: Filipino breakfast delight with thinly sliced beef in soy-garlic marinade. Perfect with garlic fried rice (sinangag) and fried eggs (itlog).",
    ingredients: [
      "1 pound beef sirloin or tenderloin, thinly sliced",
      "1/4 cup soy sauce",
      "3 tablespoons vinegar",
      "3 tablespoons brown sugar",
      "4 cloves garlic, minced",
      "1 teaspoon ground black pepper",
      "1/2 teaspoon salt",
      "Cooking oil for frying",
      "Garlic fried rice (sinangag) and fried eggs (itlog) for serving",
    ],
    instructions: [
      "In a bowl, combine soy sauce, vinegar, brown sugar, minced garlic, black pepper, and salt. Mix well until the sugar is dissolved.",
      "Add the thinly sliced beef to the marinade, ensuring each piece is well-coated. Marinate the beef for at least 2 hours or overnight in the refrigerator for better flavor absorption.",
      "In a pan over medium heat, add cooking oil. Fry the marinated beef slices until browned and caramelized, ensuring they are cooked to your desired level of doneness.",
      "Serve the Beef Tapa hot over a bed of garlic fried rice (sinangag) and with fried eggs (itlog) on the side.",
      "Enjoy this delicious and savory Filipino breakfast dish!",
    ],
    cookTime: "20 minutes",
    image: "beef_tapa.jpg",
    category: "Beef",
    iframe: "https://www.youtube.com/embed/BuyJxuHPy1c?si=4jSqHb74c5HDt7aj",
  },
  {
    id: 20,
    name: "Chicken Curry",
    description:
      "A flavorful and aromatic chicken curry that combines tender chicken with a rich blend of spices and coconut milk.",
    ingredients: [
      "2 lbs chicken, cut into pieces",
      "1 large onion, finely chopped",
      "3 cloves garlic, minced",
      "1-inch ginger, grated",
      "2 tomatoes, chopped",
      "1/4 cup curry powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1/2 teaspoon chili powder (adjust to taste)",
      "1 can (14 oz) coconut milk",
      "Salt and pepper to taste",
      "2 tablespoons cooking oil",
      "Fresh cilantro for garnish",
      "Cooked rice for serving",
    ],
    instructions: [
      "In a large pot, heat cooking oil over medium heat. Add chopped onions, minced garlic, and grated ginger. Sauté until onions are translucent.",
      "Add chicken pieces to the pot and cook until they are browned on all sides.",
      "Stir in curry powder, turmeric powder, cumin powder, coriander powder, and chili powder. Cook for 2-3 minutes until the spices are fragrant.",
      "Add chopped tomatoes and cook until they are soft and the mixture becomes slightly thickened.",
      "Pour in the coconut milk and season with salt and pepper. Bring the curry to a simmer and let it cook for about 20-25 minutes or until the chicken is cooked through.",
      "Garnish the chicken curry with fresh cilantro and serve hot over a bed of cooked rice.",
      "Enjoy this delicious and aromatic Chicken Curry!",
    ],
    cookTime: "45 minutes",
    image: "chicken_curry.jpg",
    category: "Chicken",
    iframe: "https://www.youtube.com/embed/PiwjzDLge8s?si=Lq6GOQ0ksbeHY90_",
  },
  {
    id: 21,
    name: "Rellenong Bangus",
    description:
      "Relyenong Bangus is a Filipino dish that features a deboned milkfish stuffed with a mixture of ground pork, vegetables, and spices, then fried to perfection.",
    ingredients: [
      "1 whole bangus (milkfish), scaled, cleaned, and deboned",
      "1/2 cup ground pork",
      "1/4 cup carrots, finely chopped",
      "1/4 cup potatoes, finely chopped",
      "1/4 cup green peas",
      "1/4 cup raisins",
      "1/4 cup bell pepper, finely chopped",
      "1/4 cup onion, finely chopped",
      "3 cloves garlic, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon fish sauce",
      "1 teaspoon ground black pepper",
      "1 teaspoon salt",
      "Cooking oil for frying",
    ],
    instructions: [
      "In a large bowl, combine ground pork, carrots, potatoes, green peas, raisins, bell pepper, onion, and garlic. Mix well.",
      "Season the mixture with soy sauce, fish sauce, ground black pepper, and salt. Mix until all ingredients are evenly distributed.",
      "Take the deboned bangus and stuff it with the pork and vegetable mixture. Sew the opening to secure the stuffing.",
      "In a pan over medium heat, heat cooking oil. Carefully place the stuffed bangus in the hot oil and fry until golden brown on all sides.",
      "Remove the stuffed bangus from the pan and place it on a plate lined with paper towels to absorb excess oil.",
      "Slice the Relyenong Bangus and serve it hot. Enjoy this delicious and savory Filipino dish!",
    ],
    cookTime: "30 minutes",
    image: "rellenong_bangus.jpg",
    category: "Seafood",
    iframe: "https://www.youtube.com/embed/fydMjrvdPAQ?si=wCUVEi4KNIS2GXdJ",
  },
  {
    id: 22,
    name: "Tonkatsu",
    description:
      "Tonkatsu is a popular Japanese dish featuring breaded and deep-fried pork cutlets served with a flavorful tonkatsu sauce and shredded cabbage.",
    ingredients: [
      "4 pork loin cutlets, boneless",
      "Salt and pepper to taste",
      "1/2 cup all-purpose flour",
      "2 large eggs, beaten",
      "1 cup panko breadcrumbs",
      "Vegetable oil for deep frying",
      "Tonkatsu sauce for serving",
      "Shredded cabbage for serving",
      "Cooked rice for serving",
    ],
    instructions: [
      "Season the pork loin cutlets with salt and pepper on both sides.",
      "Dredge each cutlet in flour, ensuring it is coated evenly. Shake off any excess flour.",
      "Dip the cutlets into the beaten eggs, covering them completely.",
      "Coat the cutlets with panko breadcrumbs, pressing the breadcrumbs onto the surface to adhere.",
      "In a deep pan, heat vegetable oil to 350°F (180°C). Carefully place the breaded pork cutlets into the hot oil and fry until golden brown and cooked through, about 4-5 minutes per side.",
      "Remove the tonkatsu from the oil and place them on a plate lined with paper towels to drain excess oil.",
      "Slice the tonkatsu into strips and serve with shredded cabbage, tonkatsu sauce, and cooked rice.",
      "Enjoy this crispy and delicious Japanese Tonkatsu!",
    ],
    cookTime: "15 minutes",
    image: "tonkatsu.jpg",
    category: "Pork",
    iframe: "https://www.youtube.com/embed/AtgqMOi2Ze4?si=G1ZALnRPUWXsYZVV",
  },
  {
    id: 23,
    name: "Pork Spring Rolls",
    description:
      "Pork Spring Rolls are delicious appetizers featuring seasoned ground pork, vermicelli noodles, and fresh vegetables wrapped in spring roll wrappers and deep-fried until golden brown.",
    ingredients: [
      "1 pound ground pork",
      "1 cup vermicelli noodles, cooked and chopped",
      "1 cup cabbage, shredded",
      "1/2 cup carrots, julienned",
      "1/2 cup mushrooms, finely chopped",
      "2 cloves garlic, minced",
      "1 tablespoon soy sauce",
      "1 tablespoon oyster sauce",
      "1 teaspoon sesame oil",
      "1 teaspoon sugar",
      "Spring roll wrappers",
      "Vegetable oil for deep frying",
      "Sweet and sour sauce for dipping",
    ],
    instructions: [
      "In a pan over medium heat, cook the ground pork until browned. Add minced garlic and cook until fragrant.",
      "Add soy sauce, oyster sauce, sesame oil, and sugar to the pork. Stir well to combine.",
      "Add cooked and chopped vermicelli noodles, shredded cabbage, julienned carrots, and chopped mushrooms to the pan. Cook until the vegetables are tender. Remove from heat and let the mixture cool.",
      "Place a spring roll wrapper on a clean surface. Spoon a portion of the pork and vegetable mixture onto the center of the wrapper.",
      "Fold the sides of the wrapper over the filling and then roll it up tightly from the bottom to form a spring roll. Seal the edges with water.",
      "Heat vegetable oil in a deep pan. Carefully place the spring rolls into the hot oil and fry until golden brown and crispy.",
      "Remove the spring rolls from the oil and place them on a plate lined with paper towels to absorb excess oil.",
      "Serve the Pork Spring Rolls hot with sweet and sour sauce for dipping.",
      "Enjoy these delicious and crispy Pork Spring Rolls as an appetizer or snack!",
    ],
    cookTime: "30 minutes",
    image: "pork_spring_rolls.jpg",
    category: "Pork",
    iframe: "https://www.youtube.com/embed/da7dIgQ76-Q?si=XHwrySWWx-CcBUHS",
  },
  {
    id: 24,
    name: "Creamy Garlic Scallops",
    description:
      "Creamy Garlic Scallops are a decadent seafood dish featuring perfectly seared scallops in a rich and flavorful creamy garlic sauce.",
    ingredients: [
      "1 pound fresh scallops, patted dry",
      "2 tablespoons butter",
      "4 cloves garlic, minced",
      "1/2 cup heavy cream",
      "1/4 cup chicken broth",
      "1 tablespoon white wine (optional)",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
      "Lemon wedges for serving",
    ],
    instructions: [
      "Season the scallops with salt and pepper on both sides.",
      "In a skillet over medium-high heat, melt 1 tablespoon of butter. Add the scallops and sear for 2-3 minutes on each side, until golden brown. Remove scallops from the skillet and set aside.",
      "In the same skillet, add the remaining butter. Saute minced garlic until fragrant.",
      "Pour in the chicken broth and white wine (if using), scraping the bottom of the skillet to release any flavorful bits. Let it simmer for 2 minutes.",
      "Reduce the heat to medium-low. Pour in the heavy cream, stirring continuously until the sauce thickens.",
      "Return the seared scallops to the skillet, coating them in the creamy garlic sauce. Cook for an additional 2-3 minutes until scallops are heated through.",
      "Garnish with fresh parsley and serve the Creamy Garlic Scallops hot, accompanied by lemon wedges.",
      "Enjoy this luxurious seafood dish as a main course with your favorite side.",
    ],
    cookTime: "15 minutes",
    image: "creamy_garlic_scallops.jpg",
    category: "Seafood",
    iframe: "https://www.youtube.com/embed/PH8Fg5XK-s4?si=e6tGDIIyef0jrK9l",
  },
  {
    id: 25,
    name: "Chicken Popcorns",
    description:
      "Chicken Popcorns are bite-sized, crispy chicken pieces seasoned to perfection. They make for a delicious snack or appetizer that's perfect for sharing.",
    ingredients: [
      "1 pound boneless, skinless chicken breasts, cut into bite-sized pieces",
      "1 cup buttermilk",
      "1 cup all-purpose flour",
      "1 teaspoon garlic powder",
      "1 teaspoon onion powder",
      "1 teaspoon paprika",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Vegetable oil for frying",
      "Dipping sauces of your choice (e.g., ranch, barbecue)",
    ],
    instructions: [
      "Place the chicken pieces in a bowl and pour buttermilk over them. Let them marinate for at least 30 minutes (or overnight in the refrigerator) to tenderize the chicken.",
      "In a separate bowl, mix together flour, garlic powder, onion powder, paprika, salt, and black pepper to create the seasoned coating for the chicken.",
      "Heat vegetable oil in a deep fryer or a large, heavy pot to 350°F (175°C).",
      "Dredge the marinated chicken pieces in the seasoned flour mixture, ensuring they are evenly coated.",
      "Carefully place the coated chicken pieces into the hot oil and fry until golden brown and crispy. Work in batches to avoid overcrowding the fryer.",
      "Remove the Chicken Popcorns from the oil using a slotted spoon and place them on a plate lined with paper towels to absorb excess oil.",
      "Serve the Chicken Popcorns hot with your favorite dipping sauces.",
      "Enjoy these crunchy and flavorful Chicken Popcorns as a snack or appetizer!",
    ],
    cookTime: "20 minutes",
    image: "chicken_popcorns.jpg",
    category: "Chicken",
    iframe: "https://www.youtube.com/embed/YPEeGkFUzOk?si=WEkTtSJ_9BjWG9mK",
  },
];

module.exports = { recipes };
