const recipes = [
  {
    id: 0,
    dish: "Pork Strips Steak",
    chef: "Kuya Fern's",
    image: "https://img.youtube.com/vi/fNMe8p8ANPQ/maxresdefault.jpg",
    video:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/fNMe8p8ANPQ?si=XPCYyEj0mM4RB54O" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
    recipe: [
      "2pcs chopped onions",
      "1head chopped garlic",
      "1 and 1/2Kilo Pork belly sliced into strips",
      "1/2tsp salt and ground black pepper",
      "5Tbsp soy sauce",
      "5Tbsp oyster sauce",
      "water enough to submerge the meat",
      "5Tbsp calamansi juice",
      "red onion rings",
    ],
    date: "January 13, 2024",
  },
  {
    id: 1,
    dish: "Batangas Beef Caldereta",
    chef: "Kuya Fern's",
    image: "https://img.youtube.com/vi/m2t8ShpEdZI/maxresdefault.jpg",
    video:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/m2t8ShpEdZI?si=HkD-0XBc3HxEaeDE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
    recipe: [
      "3Tbsp margarine",
      "4pcs chopped onions",
      "1head chopped garlic",
      "2Tbsp tomato paste",
      "2.1Kilo beef Camto sliced into chunky cubes",
      "1tsp salt and ground black pepper",
      "4Tbsp soy sauce",
      "4 and 1/2Tbsp oyster sauce",
      "2Tbsp Worcestershire sauce",
      "water enough to almost submerge the meat. Add more water as needed",
      "85g liver spread",
      "100g sweet pickle relish",
      "80g grated cheese",
      "2Tbsp dried chili flakes (add more depending on preference)",
    ],
    date: "January 14, 2024",
  },
  {
    id: 2,
    dish: "Spicy Ginataang Manok",
    chef: "Kuya Fern's",
    image: "https://img.youtube.com/vi/uUFGC7luNRw/maxresdefault.jpg",
    video:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/uUFGC7luNRw?si=BjU-cnP6cT6WoYil" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
    recipe: [
      "2pcs chopped onions",
      "8cloves chopped garlic",
      "1.5Kilo chicken legs and thigs",
      "1/2tsp salt and ground black pepper",
      "3Tbsp soy sauce",
      "3Tbsp oyster sauce",
      "400g (net weight) canned mushroom",
      "almost 1Cup water",
      "1 and 1/2Cup pure coconut milk",
      "chili flakes",
      "2handful malunggay leaves",
    ],
    date: "January 14, 2024",
  },
  {
    id: 3,
    dish: "Sauteed Pork",
    chef: "Kuya Fern's",
    image: "https://img.youtube.com/vi/c7q46WwmCsg/maxresdefault.jpg",
    video:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/c7q46WwmCsg?si=X-ALvAiT02_E0AbJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
    recipe: [
      "sliced string beans",
      "1/4tsp salt and ground black pepper",
      "2pcs chopped onions",
      "8cloves chopped garlic",
      "3pcs sliced red tomatoes",
      "1Kilo pork belly sliced into strips",
      "1/2tsp salt and ground black pepper",
      "4Tbsp fish sauce",
      "water enough to submerge meat (add more as needed)",
      "about 600-650g sliced squash",
    ],
    date: "January 14, 2024",
  },
];

module.exports = { recipes };
